### ISSUE TITLE
Broken paramaterized pragma parsing

### ISSUE THREAD

**Issue by lukas0008** [tursodatabase/limbo#1540]
## Issue
While using params in a query, setting a pragma statement causes an `SqlExecutionFailure` (more specifically: a syntax error)
f.e. `PRAGMA user_version = ?`

## Reproducing
In a default binary project:

`src/main.rs`
```rust
use limbo::params;

#[tokio::main]
async fn main() {
    let db = limbo::Builder::new_local("test.db").build().await.unwrap();

    let conn = db.connect().unwrap();

    conn.execute("PRAGMA page_size = ?", params!(512))
        .await
        .unwrap();
}
```

`Cargo.toml`
```toml
[package]
name = "limbo-issue"
version = "0.1.0"
edition = "2024"

[dependencies]
limbo = "0.0.20"
tokio = { version = "1.45.0", features = ["full"] }
```
### Output
```
thread 'main' panicked at src\main.rs:11:10:
called `Result::unwrap()` on an `Err` value: SqlExecutionFailure("near \"\": syntax error at (1, 21)")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This bevaiour also occurs when using numbered and named params.
